name: Build and deploy
on:
   push:
      branches:
      - develop
      - release/**
   workflow_dispatch: null
env:
   MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
   MVN_CLI_ARGS: --batch-mode --update-snapshots
   GITHUB_TOKEN: ${{github.token}}
   SECRETS_MAVEN_UPLOAD_SNAPSHOT_URL: ${{secrets.MAVEN_UPLOAD_SNAPSHOT_URL}}
   SECRETS_MAVEN_UPLOAD_RELEASE_URL: ${{secrets.MAVEN_UPLOAD_RELEASE_URL}}
jobs:
   build-and-deploy:
      if: github.event_name == 'workflow_dispatch' || !contains(github.event.head_commit.message, 'skip ci')
      runs-on: ubuntu-latest
      steps:
      -  name: Check out corresponding commit
         uses: actions/checkout@v2
      -  name: Set up Java 11 and Maven (for deploying to GitHub Packages)
         if: env.SECRETS_MAVEN_UPLOAD_SNAPSHOT_URL == null || env.SECRETS_MAVEN_UPLOAD_RELEASE_URL == null
         uses: actions/setup-java@v1
         with:
            java-version: 11
            server-id: maven-upload
      -  name: Set up Java 11 and Maven (for deploying to a custom repository)
         if: env.SECRETS_MAVEN_UPLOAD_SNAPSHOT_URL != null && env.SECRETS_MAVEN_UPLOAD_RELEASE_URL != null
         uses: actions/setup-java@v1
         with:
            java-version: 11
            server-id: maven-upload
            server-username: MAVEN_UPLOAD_USERNAME
            server-password: MAVEN_UPLOAD_PASSWORD
      -  name: Set up cache
         uses: actions/cache@v2
         with:
            path: ~/.m2/repository
            key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
      -  name: Build and deploy project (to GitHub Packages)
         if: env.SECRETS_MAVEN_UPLOAD_SNAPSHOT_URL == null || env.SECRETS_MAVEN_UPLOAD_RELEASE_URL == null
         run: .github/workflows/mvn-deploy.sh
         env:
            MAVEN_UPLOAD_SNAPSHOT_URL: https://maven.pkg.github.com/${{github.repository}}
            MAVEN_UPLOAD_RELEASE_URL: https://maven.pkg.github.com/${{github.repository}}
      -  name: Build and deploy project (to a custom repository)
         if: env.SECRETS_MAVEN_UPLOAD_SNAPSHOT_URL != null && env.SECRETS_MAVEN_UPLOAD_RELEASE_URL != null
         run: .github/workflows/mvn-deploy.sh
         env:
            MAVEN_UPLOAD_SNAPSHOT_URL: ${{secrets.MAVEN_UPLOAD_SNAPSHOT_URL}}
            MAVEN_UPLOAD_RELEASE_URL: ${{secrets.MAVEN_UPLOAD_RELEASE_URL}}
            MAVEN_UPLOAD_USERNAME: ${{secrets.MAVEN_UPLOAD_USERNAME}}
            MAVEN_UPLOAD_PASSWORD: ${{secrets.MAVEN_UPLOAD_PASSWORD}}