#!/bin/bash

echo ">>> Building project and distributing the package ..."
[[ -n "${INPUT_OVERRIDEUSECUSTOMMAVENDISTRIBUTION}" ]] && USE_CUSTOM_MAVEN_DISTRIBUTION=${INPUT_OVERRIDEUSECUSTOMMAVENDISTRIBUTION}
if [[ "${USE_CUSTOM_MAVEN_DISTRIBUTION}" != "true" ]]
then
	export MAVEN_DISTRIBUTION_SNAPSHOTS_URL=https://maven.pkg.github.com/${GITHUB_REPOSITORY}
	export MAVEN_DISTRIBUTION_RELEASES_URL=https://maven.pkg.github.com/${GITHUB_REPOSITORY}
	export MAVEN_DISTRIBUTION_USERNAME=${GITHUB_ACTOR}
	export MAVEN_DISTRIBUTION_PASSWORD=${GITHUB_TOKEN}
fi
mvn ${MVN_CLI_ARGS} clean deploy
echo ">>> Done."
