name: Perform release
on:
  workflow_dispatch:
    inputs:
      doUploadToAdditionalRepo:
        description: Do upload to an additional repo?
        required: true
        default: 'false'
      doDeploySite:
        description: Do site deployment?
        required: true
        default: 'false'
env:
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  MVN_CLI_ARGS: --batch-mode --update-snapshots
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  perform-release:
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.PERSONAL_ACCESS_TOKEN_GITHUB}}
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
    - run: .github/workflows/git-config-user.sh
    - run: .github/workflows/perform-release.sh
    - run: .github/workflows/upload-release.sh
      if: github.event.inputs.doUploadToAdditionalRepo == 'true'
      env:
        MAVEN_SETTINGS_FILE: .github/workflows/maven-settings.xml
        MAVEN_SERVER_ID: additional-server
        MAVEN_SERVER_USERNAME: ${{secrets.MAVEN_SERVER_USERNAME}}
        MAVEN_SERVER_PASSWORD: ${{secrets.MAVEN_SERVER_PASSWORD}}
        MAVEN_UPLOAD_URL_TEMPLATE: ${{secrets.MAVEN_UPLOAD_URL_TEMPLATE}}
    - run: .github/workflows/deploy-site.sh
      if: github.event.inputs.doDeploySite == 'true'