name: Perform release
on:
   workflow_dispatch:
      inputs:
         doSiteDeployment:
            description: Do site deployment?
            required: true
            default: 'false'
         overrideUseCustomMavenDistribution:
            description: Override USE_CUSTOM_MAVEN_DISTRIBUTION
env:
   MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
   MVN_CLI_ARGS: --batch-mode --update-snapshots
   GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
   USE_CUSTOM_MAVEN_DISTRIBUTION: ${{secrets.USE_CUSTOM_MAVEN_DISTRIBUTION}}
   OVERRIDE_USE_CUSTOM_MAVEN_DISTRIBUTION: ${{github.event.inputs.overrideUseCustomMavenDistribution}}
   MAVEN_DISTRIBUTION_SNAPSHOTS_URL: ${{secrets.MAVEN_DISTRIBUTION_SNAPSHOTS_URL}}
   MAVEN_DISTRIBUTION_RELEASES_URL: ${{secrets.MAVEN_DISTRIBUTION_RELEASES_URL}}
   MAVEN_DISTRIBUTION_USERNAME: ${{secrets.MAVEN_DISTRIBUTION_USERNAME}}
   MAVEN_DISTRIBUTION_PASSWORD: ${{secrets.MAVEN_DISTRIBUTION_PASSWORD}}
jobs:
   perform-release:
      if: startsWith(github.ref, 'refs/heads/release/')
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
         with:
            token: ${{secrets.GH_WORKFLOW_TOKEN}}
      -  uses: actions/setup-java@v1
         with:
            java-version: 11
            server-id: maven-distribution
            server-username: MAVEN_DISTRIBUTION_USERNAME
            server-password: MAVEN_DISTRIBUTION_PASSWORD
      -  uses: actions/cache@v2
         with:
            path: ~/.m2/repository
            key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
      -  run: .github/workflows/check-maven-distribution-settings.sh
      -  run: .github/workflows/configure-git-user.sh
      -  run: .github/workflows/perform-release.sh
      -  run: .github/workflows/deploy-site.sh
         if: github.event.inputs.doSiteDeployment == 'true'