name: Perform release
on:
   workflow_dispatch:
      inputs:
         doSiteDeployment:
            description: Do site deployment?
            required: true
            default: 'false'
env:
   MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
   MVN_CLI_ARGS: --batch-mode --update-snapshots
   GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
   SECRETS_MAVEN_UPLOAD_SNAPSHOT_URL: ${{secrets.MAVEN_UPLOAD_SNAPSHOT_URL}}
   SECRETS_MAVEN_UPLOAD_RELEASE_URL: ${{secrets.MAVEN_UPLOAD_RELEASE_URL}}
jobs:
   perform-release:
      if: startsWith(github.ref, 'refs/heads/release/')
      runs-on: ubuntu-latest
      steps:
      -  name: Check out corresponding commit
         uses: actions/checkout@v2
         with:
            token: ${{secrets.GH_WORKFLOW_TOKEN}}
      -  name: Set up Java 11 and Maven (for deploying to GitHub Packages)
         if: env.SECRETS_MAVEN_UPLOAD_SNAPSHOT_URL == null || env.SECRETS_MAVEN_UPLOAD_RELEASE_URL == null
         uses: actions/setup-java@v1
         with:
            java-version: 11
            server-id: maven-upload
      -  name: Set up Java 11 and Maven (for deploying to a custom repository)
         if: env.SECRETS_MAVEN_UPLOAD_SNAPSHOT_URL != null && env.SECRETS_MAVEN_UPLOAD_RELEASE_URL != null
         uses: actions/setup-java@v1
         with:
            java-version: 11
            server-id: maven-upload
            server-username: MAVEN_UPLOAD_USERNAME
            server-password: MAVEN_UPLOAD_PASSWORD
      -  name: Set up cache
         uses: actions/cache@v2
         with:
            path: ~/.m2/repository
            key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
      -  name: Configure git user
         run: .github/workflows/git-config-user.sh
      -  name: Perform release (with deploying to GitHub Packages)
         if: env.SECRETS_MAVEN_UPLOAD_SNAPSHOT_URL == null || env.SECRETS_MAVEN_UPLOAD_RELEASE_URL == null
         run: .github/workflows/perform-release.sh
         env:
            MAVEN_UPLOAD_SNAPSHOT_URL: https://maven.pkg.github.com/${{github.repository}}
            MAVEN_UPLOAD_RELEASE_URL: https://maven.pkg.github.com/${{github.repository}}
      -  name: Perform release (with deploying to a custom repository)
         if: env.SECRETS_MAVEN_UPLOAD_SNAPSHOT_URL != null && env.SECRETS_MAVEN_UPLOAD_RELEASE_URL != null
         run: .github/workflows/perform-release.sh
         env:
            MAVEN_UPLOAD_SNAPSHOT_URL: ${{secrets.MAVEN_UPLOAD_SNAPSHOT_URL}}
            MAVEN_UPLOAD_RELEASE_URL: ${{secrets.MAVEN_UPLOAD_RELEASE_URL}}
            MAVEN_UPLOAD_USERNAME: ${{secrets.MAVEN_UPLOAD_USERNAME}}
            MAVEN_UPLOAD_PASSWORD: ${{secrets.MAVEN_UPLOAD_PASSWORD}}
      -  name: Deploy site to GitHub Pages
         if: github.event.inputs.doSiteDeployment == 'true'
         run: .github/workflows/deploy-site.sh