name: Perform release
on:
   workflow_dispatch:
      inputs:
         overrideMavenDistributionType:
            description: Override MAVEN_DISTRIBUTION_TYPE
            required: false
         doSiteDeployment:
            description: Do site deployment?
            required: true
            default: 'false'
env:
   GITHUB_TOKEN: ${{github.token}}
   MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
   MAVEN_DEFAULT_ARGS: --batch-mode --update-snapshots
   GIT_USER_NAME: GitHub Actions (${{github.actor}})
   GIT_USER_EMAIL: ${{github.actor}}.actions@users.noreply.github.com
jobs:
   perform-maven-release:
      if: startsWith(github.ref, 'refs/heads/release/')
      runs-on: ubuntu-latest
      outputs:
         releaseVersion: ${{steps.store-release-version.outputs.releaseVersion}}
      steps:
      -  uses: actions/checkout@v2
         with:
            token: ${{secrets.GH_WORKFLOW_TOKEN}}
      -  uses: actions/setup-java@v1
         with:
            java-version: 11
            server-id: maven-distribution
            server-username: MAVEN_DISTRIBUTION_USERNAME
            server-password: MAVEN_DISTRIBUTION_PASSWORD
      -  uses: actions/cache@v2
         with:
            path: ~/.m2/repository
            key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
      -  run: .github/workflows/scripts/configure-git-user.sh
      -  run: .github/workflows/scripts/perform-maven-release.sh
         env:
            MAVEN_ADDITIONAL_ARGS: -Dreleasing
            TAG_NAME_FORMAT: '@{project.version}'
            NEXT_DEVELOPMENT_VERSION: ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion}-SNAPSHOT
            SCM_COMMENT_PREFIX: '[skip ci] '
            OVERRIDE_MAVEN_DISTRIBUTION_TYPE: ${{github.event.inputs.overrideMavenDistributionType}}
            MAVEN_DISTRIBUTION_TYPE: ${{secrets.MAVEN_DISTRIBUTION_TYPE}}
            MAVEN_DISTRIBUTION_SNAPSHOTS_URL: ${{secrets.MAVEN_DISTRIBUTION_SNAPSHOTS_URL}}
            MAVEN_DISTRIBUTION_RELEASES_URL: ${{secrets.MAVEN_DISTRIBUTION_RELEASES_URL}}
            MAVEN_DISTRIBUTION_USERNAME: ${{secrets.MAVEN_DISTRIBUTION_USERNAME}}
            MAVEN_DISTRIBUTION_PASSWORD: ${{secrets.MAVEN_DISTRIBUTION_PASSWORD}}
      -  name: Store release version
         id: store-release-version
         run: .github/workflows/scripts/store-project-version.sh
         env:
            OUTPUT_VARIABLE_NAME: releaseVersion
            PROJECT_DIRECTORY: target/checkout
   generate-and-deploy-maven-site:
      needs: perform-maven-release
      if: github.event.inputs.doSiteDeployment == 'true'
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
         with:
            ref: ${{needs.perform-maven-release.outputs.releaseVersion}}
      -  uses: actions/setup-java@v1
         with:
            java-version: 11
      -  uses: actions/cache@v2
         with:
            path: ~/.m2/repository
            key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
      -  run: .github/workflows/scripts/configure-git-user.sh
      -  run: .github/workflows/scripts/generate-and-deploy-maven-site.sh
         env:
            MAVEN_ADDITIONAL_ARGS: -DdeployingSite