name: Prepare release
on: workflow_dispatch
jobs:
   create-release-branch:
      if: github.ref == 'refs/heads/develop'
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
      -  uses: actions/setup-java@v1
         with:
            java-version: 11
      -  uses: actions/cache@v2
         with:
            path: ~/.m2/repository
            key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
            restore-keys: ${{runner.os}}-maven-
      -  run: .github/workflows/scripts/configure-git-user.sh
      -  run: .github/workflows/scripts/create-release-branch.sh
         env:
            MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
            RELEASE_BRANCH_NAME: release/${parsedVersion.majorVersion}.${parsedVersion.minorVersion}
   increment-development-version:
      if: github.ref == 'refs/heads/develop'
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
         with:
            token: ${{secrets.GH_WORKFLOW_TOKEN}}
      -  uses: actions/setup-java@v1
         with:
            java-version: 11
      -  uses: actions/cache@v2
         with:
            path: ~/.m2/repository
            key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
            restore-keys: ${{runner.os}}-maven-
      -  run: .github/workflows/scripts/configure-git-user.sh
      -  run: .github/workflows/scripts/increment-development-version.sh
         env:
            MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
            NEXT_DEVELOPMENT_VERSION: ${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}-SNAPSHOT
            GIT_COMMIT_MESSAGE: Starting next development iteration.