name: Prepare release
on: workflow_dispatch
env:
   MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
   MVN_CLI_ARGS: --batch-mode --update-snapshots
   GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
   prepare-release:
      if: github.ref == 'refs/heads/develop'
      runs-on: ubuntu-latest
      steps:
      -  name: Check out corresponding commit
         uses: actions/checkout@v2
         with:
            token: ${{secrets.GH_WORKFLOW_TOKEN}}
      -  name: Set up Java 11 and Maven
         uses: actions/setup-java@v1
         with:
            java-version: 11
      -  name: Set up cache
         uses: actions/cache@v2
         with:
            path: ~/.m2/repository
            key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
      -  name: Configure git user
         run: .github/workflows/git-config-user.sh
      -  name: Prepare release
         run: .github/workflows/prepare-release.sh