#!/bin/bash

GITHUB_REPO_OWNER=${GITHUB_REPOSITORY%/*}
GITHUB_REPO_NAME=${GITHUB_REPOSITORY#*/}

UPLOAD_URL=${UPLOAD_URL_TEMPLATE//%%GITHUB_ACTOR%%/$GITHUB_ACTOR}
UPLOAD_URL=${UPLOAD_URL//%%GITHUB_REPO_OWNER%%/$GITHUB_REPO_OWNER}
UPLOAD_URL=${UPLOAD_URL//%%GITHUB_REPO_NAME%%/$GITHUB_REPO_NAME}

cd target/checkout
mvn ${MVN_CLI_ARGS} --settings "${MAVEN_SETTINGS_FILE}" verify source:jar javadoc:jar deploy:deploy \
		-Duploading \
		-DskipTests \
		-DaltDeploymentRepository="${MAVEN_SERVER_ID}::${UPLOAD_URL}"
		